name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: |
        tomcat:8.5.31
        maven:3.5.3
      ports: 
        - 8081
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
#   test:
#     needs: build
#     runs-on: ubuntu-latest
#     container:
#       image: tomcat:8.5.31
#       ports: 8081
#     steps:
#       - uses: actions/checkout@v1
#       - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8
      
